### ISSUE TITLE
Eco Init command behaves strangely

### ISSUE THREAD

**Issue by ghost** [hotmeteor/eco-cli#7]
# Eco init saves invalid access tokens
When eco-cli is installed globally (I haven't tested per-project) using eco init works and saves the token to the .eco/config.json file. At first I input an invalid access token and the couldn't connect error was displayed. However the bad token was still saved to the config.json file.

# Eco init only allows one saved configuration per service
When I re-ran eco init choosing gitlab again the command read the config.json file and saw there was already a saved token for the gitlab service and so it used the same token and then immediately displayed the couldn't connect error without giving the option to change the token. This also means that there is no way for a user to connect to more than one github account because the drivers are stored with the service name as the key

# eco init shows an error after the organization is selected
I input the string of numbers representing the organization and recieved this error:
```
Which organization should be used?:
  [1234567] ORG_NAME
 > 1234567

Organization set successfully.
[2020-09-28 15:54:09] development.ERROR: Choice question must have at least 1 choice available. {"exception":"[object] (LogicException(code: 0): Choice question must have at least 1 choice available. at /root/.composer/vendor/symfony/console/Question/ChoiceQuestion.php:36)
[stacktrace]
#0 /root/.composer/vendor/illuminate/console/Concerns/InteractsWithIO.php(207): Symfony\\Component\\Console\\Question\\ChoiceQuestion->__construct()
#1 /root/.composer/vendor/hotmeteor/eco-cli/app/Concerns/AsksForRepository.php(29): Illuminate\\Console\\Command->choice()
#2 /root/.composer/vendor/hotmeteor/eco-cli/app/Concerns/AsksForRepository.php(18): App\\Commands\\InitCommand->getRepositoryChoice()
#3 /root/.composer/vendor/hotmeteor/eco-cli/app/Commands/InitCommand.php(87): App\\Commands\\InitCommand->asksForRepository()
#4 /root/.composer/vendor/hotmeteor/eco-cli/app/Commands/InitCommand.php(50): App\\Commands\\InitCommand->ensureCurrentRepoIsSet()
#5 [internal function]: App\\Commands\\InitCommand->handle()
#6 /root/.composer/vendor/illuminate/container/BoundMethod.php(37): call_user_func_array()
#7 /root/.composer/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /root/.composer/vendor/illuminate/container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /root/.composer/vendor/illuminate/container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /root/.composer/vendor/illuminate/container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#11 /root/.composer/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call()
#12 /root/.composer/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#13 /root/.composer/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /root/.composer/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#15 /root/.composer/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /root/.composer/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#17 /root/.composer/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#18 /root/.composer/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#19 /root/.composer/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 /root/.composer/vendor/hotmeteor/eco-cli/eco(37): LaravelZero\\Framework\\Kernel->handle()
#21 {main}
"}
```

**Comment by hotmeteor** [comment]
@cole-flexsim Thanks. That's odd, I wonder if it's a conflict with the old config format.

Can you try deleting the `~/.eco/config.json` file and starting again?

**Comment by ghost** [comment]
I ran this test inside of a docker container so I had a fresh version of the package and no existing ~/.eco/config.json. Curl wasn't working on my physical machine because of an external problem I haven't fixed yet. Here is what is in my config.json after running the command and getting the error above. If I re-run eco init after this is in the config.json and choose github again it skips the token prompt and then just displays the organization prompt. Then the same error occurs

```
{
    "version": "unreleased",
    "driver": "github",
    "drivers": {
        "github": {
            "token": "TOKEN",
            "org": "ORG_NAME"
        }
    }
}
```

**Comment by hotmeteor** [comment]
@cole-flexsim 0.2.2 has a fix for not storing credentials when they are bad. Not sure if this will resolve your issue, I wasn't able to replicate what you described. I'll probably add a "logout" command to clear credentials.

> eco init shows an error after the organization is selected

This may be an issue with your org not having any repos available... not sure. Is that the case?

**Comment by ghost** [comment]
Yeah that solved the problem with the error after the organization
